### PR TITLE
Switch from travis deploy to gihub actions deployment

### PR DESCRIPTION
**Pull request by AndreG-P**

### CODE REVIEW

**Comment by AndreG-P** [comment]
@physikerwelt any idea why acm docker call exits with exit code 5? The other docker calls seem to work just fine, only 
```
Generating the spellcheck file
Unable to find image 'aggipp/textidote:latest' locally
```
begin to fail.

**Comment by AndreG-P** [comment]
@physikerwelt 
Locally it's the same. When I run
```
docker run --rm --volume "`pwd`:/data" --user `id -u`:`id -g` aggipp/textidote --check en --dict myWords.txt --output html preprint.tex > spellcheck.html
```
The entire thing runs and also creates the `spellcheck.html`. Also my console does not show any problem but if I check the previous exit code:
```bash
andreg-p@AGP-ThinkPad-T460p:~/latexPaperTemplate$ echo $?
5
```
As you can see the exit code is 5. So I only assume that travis might ignore exit code 5 but github takes it as an error?

Exit code 5 means: Access denied.

**Review by physikerwelt — COMMENTED** [review]
See https://github.com/sylvainhalle/textidote/issues/112#issuecomment-561621053
Maybe we just need to update our texidote container

**Comment by physikerwelt** [comment]
it seems there is a problem with release tag

**Pull request merged**
